carrental/car/urls.py
from django.urls import path
from car.views import (
                    home, 
                    listing, 
                    testimonials, 
                    about, 
                    contact, 
                    blog, 
                    singleBlog, 
                    ListingView, 
                    CarDetailView, 
                    order, 
                    RentFormView, 
                    IndexView, 
                    BookingListView, 
                    BookingDetailView, 
                    BookingCancelView,
                    SearchViewAjax, 
                    test, 
                    send_mail_to_all, 
                    schedule_mail)
from car.utils import msgfromoutside
app_name = 'car'

urlpatterns = [
    # for index
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # for search and list operations
    path('listing/', ListingView.as_view(), name='listing'),
    path('searchview/',SearchViewAjax.as_view(),name='searchviewajax'),

    # for rent operations
    path('cardetail/<int:pk>', CarDetailView.as_view(), name='cardetail'),
    path('rent/', RentFormView.as_view(), name='rent'),

    # for bookings operations
    path('bookings/', BookingListView.as_view(), name='bookings'),
    path('bookingdetail/<int:pk>', BookingDetailView.as_view(), name='bookingdetail'),
    path('bookingcancel/<int:pk>', BookingCancelView.as_view(), name='bookingcancel'),

    # for celery learning
    path('test/', test, name='test'),
    path('sendmail/', send_mail_to_all, name='sendmail'),
    path('schedulemail/', schedule_mail, name='schedulemail'),


    # for template testing only
    path('home/', home, name='home'),
    path('alllisting/', listing, name='alllisting'),
    path('testimonials/', testimonials, name='testimonials'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('blog/', blog, name='blog'),
    path('single/', singleBlog, name='single'),


    path('msg/', msgfromoutside, name='msg')
]

carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import LoginView, LogoutView

from django.conf.urls import handler400, handler403, handler404, handler500
from base.views import handler403 as customhandler403
from base.views import handler404 as customhandler404

# JWT Auth imports
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('', include('car.urls')),
    path('hostuser/', include('hostuser.urls')),

    path('account/login/', LoginView.as_view(), name='account_login'),
    path('account/logout/', LogoutView.as_view(), name='account_logout'),
    
    # for giving login option in api page
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),

    # ===============================
    # JWT AUTHENTICATION VIEWS URLS #
    # ===============================
    path('gettoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # For generate token JWT = http POST http://127.0.0.1:8000/gettoken/ username="<username>" password="<password>"
    
    path('refreshtoken/', TokenRefreshView.as_view(), name='token_refresh'),
    # For refresh token JWT = http POST http://127.0.0.1:8000/refreshtoken/ refresh="<refresh token>"


    path('verifytoken/', TokenVerifyView.as_view(), name='token_verify'),
    # For verify token JWT = http POST http://127.0.0.1:8000/verifytoken/ token="<access token>"

    path('api/user/', include('user.api.urls')),
    path('api/car/', include('car.api.urls')),
]

handler404 = handler400 = handler500 = customhandler404            
handler403 = customhandler403


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrental/hostuser/urls.py
from django.urls import path
from hostuser.views import (
                            DashboardView, 
                            AjaxRevenueChartDataView,
                            HostCarDetailView, 
                            HostUserProfileUpdateView,
                            HostProfileImageUpdateView, 
                            CarListView, 
                            CarListDataTablesAjaxPagination,
                            CarUpdateView, 
                            CarDeleteView, 
                            HostBookingListView, 
                            HostBookingListDataTablesAjaxPagination,
                            HostBookingDetailView, 
                            HostBookingUpdateView, 
                            CarHoldTimeCreateView, 
                            HoldCarListView, 
                            HoldCarListDataTablesAjaxPagination,
                            CarHoldTimeUpdateView, 
                            CarHoldTimeDeleteView,
                            AjaxCarAvailabilityCheckView,
                            CustomersListView,
                            CustomersListDataTablesAjaxPagination,
                            SingleCarImageDeleteView,
                            RevenueCompareView,
                            RevenueCompareAjax,
                            PasswordsChangeView,
                            PasswordsChangeDoneView,
                            NotificationReadAjaxView,
                        )
# from car.views import HostCarDeleteView

app_name = 'hostuser'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('revenue-chart-ajax/', AjaxRevenueChartDataView.as_view(), name='revenue-chart-ajax'),

    # car CRUD (Car create view is inside user app)
    path('carlist/', CarListView.as_view(), name='carlist'),
    path('car-list-ajax/',CarListDataTablesAjaxPagination.as_view(), name='car-list-ajax'),
    path('carupdate/<int:pk>', CarUpdateView.as_view(), name='carupdate'),
    path('hostcardetail/<int:pk>', HostCarDetailView.as_view(), name='hostcardetail'),
    path('cardelete/<int:pk>', CarDeleteView.as_view(), name='cardelete'),
    path('singlecarimagedelete/<int:pk>', SingleCarImageDeleteView.as_view(), name='singlecarimagedelete'),

    # update profile
    path('hostprofile/<int:pk>', HostUserProfileUpdateView.as_view(), name='hostprofile'),
    path('hostprofileimageupdate/<int:pk>', HostProfileImageUpdateView.as_view(), name='hostprofileimageupdate'),

    # booking CRUD
    path('hostbookinglist/', HostBookingListView.as_view(), name='hostbookinglist'),
    path('booking-list-ajax/',HostBookingListDataTablesAjaxPagination.as_view(), name='booking-list-ajax'),
    path('hostbookingdetail/<int:pk>', HostBookingDetailView.as_view(), name='hostbookingdetail'),
    path('hostbookingupdate/<int:pk>', HostBookingUpdateView.as_view(), name='hostbookingupdate'),

    # car hold CRUD
    path('carhold/', CarHoldTimeCreateView.as_view(), name='carhold'),
    path('holdcarlist/', HoldCarListView.as_view(), name='holdcarlist'),
    path('hold-car-list-ajax/',HoldCarListDataTablesAjaxPagination.as_view(), name='hold-car-list-ajax'),
    path('carholdupdate/<int:pk>', CarHoldTimeUpdateView.as_view(), name='carholdupdate'),
    path('carholddelete/<int:pk>', CarHoldTimeDeleteView.as_view(), name='carholddelete'),

    # check car availability using ajax
    path("ajax-car-availability/", AjaxCarAvailabilityCheckView.as_view(),  name="ajax_car_availability_check"),

    # customers list
    path('customerslist/', CustomersListView.as_view(), name='customerslist'),
    path('customers-list-ajax/',CustomersListDataTablesAjaxPagination.as_view(), name='customers-list-ajax'),

    # revenue compare
    path('revenue-compare/', RevenueCompareView.as_view(), name="revenue-compare"),
    path('revenue-compare-ajax/', RevenueCompareAjax.as_view(), name="revenue-compare-ajax"),


    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),

    # notification
    path('notification_read_status/', NotificationReadAjaxView.as_view(), name='notification_read_status'),
]

carrental/user/urls.py
from django.urls import path
from user.views import (
                        UserRegisterView, 
                        registerOptionView, 
                        RegisterOptionView,
                        LoginView, 
                        CarRegisterView,
                        UserProfileUpdateView,
                        ProfileImageUpdateView,
                        PasswordsChangeView,
                        PasswordsChangeDoneView,
                        )

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('account/login/', LoginView.as_view(), name='login'),

    # path('registeroption/', registerOptionView, name='registeroption'),
    path('registeroption/', RegisterOptionView.as_view(), name='registeroption'),
    path('carregister/', CarRegisterView.as_view(), name='carregister'),

    # update profile
    path('profile/<int:pk>', UserProfileUpdateView.as_view(), name='profile'),
    path('profileimageupdate/<int:pk>', ProfileImageUpdateView.as_view(), name='profileimageupdate'),

    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),
]

carrental/car/models.py
from django.db import models
from base.models import BaseModel
from user.models import User
from django.urls import reverse_lazy

# Create your models here.


class Car(BaseModel):
    '''Car model'''
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_owner')
    brand = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    manufacture_year = models.PositiveIntegerField()
    FUEL_TYPES = (
        ("PETROL", "Petrol"),
        ("DIESEL", "Diesel"),
        ("CNG", "CNG"),
        ("EV", "Electric"),
    )
    fuel_type = models.CharField(max_length=256, choices=FUEL_TYPES, default="PETROL")
    TRANSMISSION_TYPES = (
        ("MANUAL", "Manual"),
        ("AUTOMATIC", "Automatic"),
    )
    transmission_type = models.CharField(max_length=256, choices=TRANSMISSION_TYPES, default="MANUAL")
    CAR_TYPES = (
        ("SEDAN", "Sedan"),
        ("HATCHBACK", "Hatchback"),
        ("SUV","SUV"),
        ("COUPE", "Coupe"),
    )
    car_type = models.CharField(max_length=256, choices=CAR_TYPES, default="SEDAN")
    seats = models.PositiveIntegerField()
    registration_no = models.CharField(max_length=10, unique=True)
    km_driven = models.PositiveBigIntegerField()
    fare = models.PositiveIntegerField()
    description = models.TextField(max_length=1000)
    pickup_address = models.TextField()
    pickup_city = models.CharField(max_length=256)
    pickup_state = models.CharField(max_length=256)
    pickup_country = models.CharField(max_length=256)
    pickup_pincode = models.CharField(max_length=256)
    is_available = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    def get_detail_url(self):
        return f"/hostuser/hostcardetail/{self.pk}"
    
    def get_update_url(self):
        return f"/hostuser/carupdate/{self.pk}"
    
    def get_delete_url(self):
        return f"/hostuser/cardelete/{self.pk}"


class CarImage(BaseModel):
    '''car images model'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car_image_set') # oldname = car_name
    car_images = models.ImageField(upload_to='car_images')

    def __str__(self):
        return self.car.name
    

class CarHoldTime(BaseModel):
    '''car hold time model for hostuser'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car_carholdtime')
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()

    # def __str__(self):
    #     return self.car.name


class Rent(BaseModel):
    '''rent model for bookings data'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name="car_rent") # oldname = car_name
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user') # oldname = user_name
    pickup_datetime = models.DateTimeField()
    # pickup_time = models.TimeField()
    # pickup_place = models.CharField(max_length=256)
    drop_datetime = models.DateTimeField()
    # drop_time = models.TimeField()
    total_hours = models.PositiveIntegerField(default=None)
    total_fare = models.FloatField()
    BOOKING_STATUS = (
        ("CONFIRMED", "Confirmed"),
        ("PICKEDUP", "Pickedup"),
        ("DROPPED", "Dropped"),
        ("CANCELLED", "Cancelled"),
    )
    booking_status = models.CharField(max_length=256, choices=BOOKING_STATUS, default="CONFIRMED")
    PAYMENT_STATUS = (
        ("COMPLETED", "Completed"),
        ("PENDING", "Pending"),
        ("CANCELLED", "Cancelled"),
        ("REFUNDED", "Refunded"),
    )
    payment_status = models.CharField(max_length=256, choices=PAYMENT_STATUS, default="PENDING")

    # def __str__(self):
    #     return self.car.car + " " + self.user


class NotificationGroup(BaseModel):
    '''create notification group'''
    name = models.CharField(max_length=100)

class Notification(BaseModel):
    '''save notification'''
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_rent')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_car')
    group = models.ForeignKey(NotificationGroup, on_delete=models.CASCADE)
    message = models.CharField(max_length=500)
    is_read = models.BooleanField(default=False)

carrental/hostuser/models.py
from django.db import models

# Create your models here.

carrental/user/models.py
from django.db import models
from base.models import BaseModel
from django.contrib.auth.models import AbstractUser

class User(BaseModel, AbstractUser):
    '''User model for register new user'''
    contact = models.CharField(max_length=10)
    is_hostuser = models.BooleanField(default=False)
    profile_image = models.ImageField(upload_to="images/user_images", null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

carrental/car/forms.py
from django import forms
from django.forms import ModelForm
from django.db import transaction
from user.models import User
from car.models import Car, CarImage, Rent

class RentForm(ModelForm):
    '''Booking create form for cardetail page'''
    class Meta:
        model = Rent
        fields = ('car', 'pickup_datetime', 'drop_datetime', 'total_fare', 'total_hours')

        widgets = {
            'car': forms.HiddenInput(),
            'total_fare': forms.TextInput(attrs={'readonly': 'true', 'class': 'form-control'}),
            'total_hours': forms.TextInput(attrs={'readonly': 'true', 'class': 'form-control'}),
            'pickup_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control', 'placeholder': 'DD/MM/YYYY, HH:MM'}),
            'drop_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control', 'placeholder': 'DD/MM/YYYY, HH:MM'})
        }



    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['car'].disabled = True
    #     self.fields['pickup_datetime'].disabled = True
    #     self.fields['drop_datetime'].disabled = True
    #     self.fields['total_fare'].disabled = True

    # @transaction.atomic
    # def save(self):
    #     rent = super().save(commit=False)
    #     rent.user = self.request.user
    #     rent.save()
    #     return rent

class CarSearchForm(forms.Form):
    '''car search form for index and listing page'''
    start_datetime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control', 'placeholder': 'DD/MM/YYYY, HH:MM'}))
    end_datetime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control', 'placeholder': 'DD/MM/YYYY, HH:MM'}))

carrental/templates/hostuser/car_hold_createform.html
{% load static %}

<!-- Start CarHold Modal -->
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Car Hold</h5>
          <button type="button" class="btn-close closebtn" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title">Car Hold Time</h5>
                    
                <!-- Car Hold Form  -->
                <form class="row g-3" action="{% url 'hostuser:carhold'  %}" method="POST" id="hold-car-form">
                    {% csrf_token %}

                    {% for error in form.non_field_errors %}
                      {{error}}
                    {% endfor %} 

                    
                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.car }}
                          {% comment %} <input type="text" class="form-control" id="id_car" value={{car.id}} readonly> {% endcomment %}
                          
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.start_datetime }}
                          {% comment %} <input type="text" class="form-control" id="floatingCity" placeholder="Brand"> {% endcomment %}
                          <label for="id_start_datetime">Start Date</label>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.end_datetime }}
                          {% comment %} <input type="text" class="form-control" id="floatingCity" placeholder="Brand"> {% endcomment %}
                          <label for="id_end_datetime">End Date</label>
                        </div>
                    </div>

                    <div id="form-error" class="text-danger"></div>
                    {% comment %} <div class="text-center d-grid gap-2 mt-5"> {% endcomment %}
                      {% comment %} <input type="submit" class="btn btn-primary" value="Submit" /> {% endcomment %}
                      {% comment %} <button type="reset" class="btn btn-secondary">Reset</button> {% endcomment %}
                    {% comment %} </div> {% endcomment %}
                  
    
                </div>
            </div>
            <input type="text" value="{{car.id}}" hidden id="car_id">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary closebtn" data-bs-dismiss="modal">Close</button>
          
            <button class="btn btn-primary check_car_availablity" id="submit-form-popup" type="submit">Submit</button>
          </form><!-- End Car Hold Form -->
        </div>
      </div>
    </div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>



    // start of date validations
      // setting min date for pickupdatetime
      var minDate = new Date().toISOString().slice(0,16);
      console.log("minDate", minDate);
    
      //To restrict past date
      $('#id_start_datetime').attr('min', minDate);
      $('#id_end_datetime').attr('min', minDate);  
      
      // setting min date for pickupdatetime

      var currentDate = new Date();
      var nextWeekDate = new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000);
      var maxDate = nextWeekDate.toISOString().slice(0, 16);
      console.log("nextWeekDate", nextWeekDate);
      console.log("maxDate", maxDate);
      //To restrict future date
      $('#id_start_datetime').attr('max', maxDate);
      $('#id_end_datetime').attr('max', maxDate);  

      // end of date validations
</script>


<script>
  $('.closebtn').on('click', function () {
    $('#hold-car-form')[0].reset();
    $("#form-error").html("");
  });


  $(document).ready(function() {
    console.log(":::::::;;;;");
    $("#id_car").val($("#car_id").val())
    $("#id_end_datetime").on('change', function(){
      console.log("::::::::::", $(this).val());
      car_id = $("#car_id").val();
      console.log("car id :", car_id);
      start_time = $("#id_start_datetime").val();
      end_time = $(this).val();

      $("#submit-form-popup").attr("disabled","true")
      $.ajax({
        url: "{% url 'hostuser:ajax_car_availability_check' %}",
        type: 'GET',
        data : {
          "car_id": car_id,
          "start_datetime": start_time,
          "end_datetime": end_time,
        },
        dataType: 'json', // added data type
        success: function(res) {
          console.log(res);
          if (res["status"] == "401"){
            $("#form-error").html(res["message"] + "<br><br>Select different dates from" + "<br>start date : " + start_time + "<br>end date : " + end_time);
            $('#hold-car-form')[0].reset();
          }
          else{
            $("#form-error").html("");
            $("#submit-form-popup").removeAttr("disabled");
          }
        }
      });
    });
  });
</script>



{% comment %} 
<script>
  $(document).ready(function() {
    $('#hold-car-form').on('submit', function(event) {
      event.preventDefault();
      const form = $(this);
      $.ajax({
        type: form.attr('method'),
        url: form.attr('action'),
        data: form.serialize(),
        dataType: 'json',
        success: function(data) {
          // handle success
          console.log("ssssssssssssssssssssssssssssss")
          console.log(data.message);
          console.log(data["status"]);
          if (data["status"] == "valid") {
            window.location.href = "/client"
          }
          if (data["status"] == "400") {
              $("#form-error").html(data["message"]);
          }
          // close modal here
        },
        error: function(data) {
          // handle errors
          console.log("eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
          console.log(data["message"]);
          alert("Error!");
          console.log(data.responseJSON);
          // Display validations error in modal
        }
      });
    });
  });
</script> {% endcomment %}

{% comment %} <script>
  $("#submit-form-popup").on("click", function(evt){
    if(evt.detail.xhr.status === 200){
      if(evt.detail.requestConfig.verb != 'get')
      {
          console.log("evt::::::::", evt)
          window.location.reload();
          
      } 
    else {
      console.log(evt)
    }
    }
  })
</script> {% endcomment %}

carrental/templates/hostuser/car_hold_updateform.html
{% extends "hostuser_base/hostuser_base.html" %}
{% load static %}

{% block title %}CarRental - Update Car {% endblock title %}

{% block content %}

<main id="main" class="main">
  {% include "messages.html" %}
  
    <div class="pagetitle">
      <h1>Update Car HoldTime</h1>
      <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hostuser:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'hostuser:holdcarlist' %}">Hold Car List</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'hostuser:carholdupdate' pk=car.id %}">Update Car HoldTime</a></li>
        </ol>
      </nav>
    </div><!-- End Page Title -->
    <section class="section">
      <div class="row">

        <!-- Dummy Col Start -->
        <div class="col-lg-2"></div>
        <!-- Dummy Col End -->

        <!-- Car Update Col Start -->
        <div class="col-lg-8">

            <div class="card">
                <div class="card-body">
                <h5 class="card-title">Update Car HoldTime</h5>
    
                <!-- Car Update Form -->
                <form class="row g-3" method="POST">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.car }}
                          {% comment %} <input type="text" class="form-control" id="id_car" value={{car.id}} readonly> {% endcomment %}
                          {% comment %} <label for="id_car">Car</label> {% endcomment %}
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.start_datetime }}
                          {% comment %} <input type="text" class="form-control" id="floatingCity" placeholder="Brand"> {% endcomment %}
                          <label for="id_start_datetime">Start Date</label>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-floating">
                          {{ form.end_datetime }}
                          {% comment %} <input type="text" class="form-control" id="floatingCity" placeholder="Brand"> {% endcomment %}
                          <label for="id_end_datetime">End Date</label>
                        </div>
                    </div>

                    <input type="text" value="{{car.id}}" hidden id="car_id">

                    <div id="form-error" class="text-danger"></div>

                    <div class="text-center d-grid gap-2 mt-5">
                      {% comment %} <input type="submit" class="btn btn-primary" value="Update" /> {% endcomment %}

                      <button class="btn btn-primary check_car_availablity" id="submit-form" type="submit">Update</button>

                      {% comment %} <button type="reset" class="btn btn-secondary">Reset</button> {% endcomment %}
                    </div>
                  </form><!-- End Car Update Form -->
    
                </div>
              </div>

        </div>
        <!-- Car Update Col End -->

        <!-- Dummy Col Start -->
        <div class="col-lg-2"></div>
        <!-- Dummy Col End -->

      </div>
    </section>

  </main><!-- End #main -->


{% endblock content %}

{% block javascripts %}

<script>

  // start of date validations
  // setting min date for pickupdatetime
  var minDate = new Date().toISOString().slice(0,16);
  console.log("minDate", minDate);

  //To restrict past date
  $('#id_start_datetime').attr('min', minDate);
  $('#id_end_datetime').attr('min', minDate);  
  
  // setting min date for pickupdatetime

  var currentDate = new Date();
  var nextWeekDate = new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000);
  var maxDate = nextWeekDate.toISOString().slice(0, 16);
  console.log("nextWeekDate", nextWeekDate);
  console.log("maxDate", maxDate);
  //To restrict future date
  $('#id_start_datetime').attr('max', maxDate);
  $('#id_end_datetime').attr('max', maxDate);  

  // end of date validations

</script>

<script>

  $(document).ready(function() {
    console.log(":::::::;;;;");
    //$("#id_car").val($("#car_id").val())
    $("#id_end_datetime").on('change', function(){
      console.log("::::::::::", $(this).val());
      car_id = $("#id_car").val();
      console.log("car id :", car_id);
      start_time = $("#id_start_datetime").val();
      end_time = $(this).val();

      $("#submit-form").attr("disabled","true")
      $.ajax({
        url: "{% url 'hostuser:ajax_car_availability_check' %}",
        type: 'GET',
        data : {
          "car_id": car_id,
          "start_datetime": start_time,
          "end_datetime": end_time,
        },
        dataType: 'json', // added data type
        success: function(res) {
          console.log(res);
          if (res["status"] == "401"){
            $("#form-error").html(res["message"] + "<br><br>Select different dates from" + "<br>start date : " + start_time + "<br>end date : " + end_time);
            $('#hold-car-form')[0].reset();
          }
          else{
            $("#form-error").html("");
            $("#submit-form").removeAttr("disabled");
          }
        }
      });
    });
  });
</script>

{% endblock javascripts %}

carrental/templates/hostuser/password_change_success.html
{% extends "hostuser_base/hostuser_base.html" %}
{% load static %}

{% block title %}CarRental - Profile {% endblock title %}

{% block content %}

<main id="main" class="main">
  {% include "messages.html" %}

  <div class="pagetitle">
    <h1>Profile</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'hostuser:dashboard' %}">Dashboard</a></li>
        <li class="breadcrumb-item active"><a href="{% url 'hostuser:hostprofile' pk=request.user.id %}">Change Password</a></li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section profile">
    <!-- Page content -->
<div class="container mt--8 pb-5">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-7">
      <div class="card bg-warning shadow border-0">
        <div class="card-header bg-transparent pb-3">
          <div class="text-muted text-center mt-2 mb-3">
            <h1>Change Password</h1>
          </div>
        </div>
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center mb-4">

            <h1 style="font-size:80px;"><i class="fas fa-check-circle" style="color: #08a108;"></i></h1>
            <h1 class="font-weight-bold my-3">Success!</h1>
            <p class="my-1 font-weight-bold">Your Password has been changed successfully.</p> 

          </div>

            <div class="text-center">
                <a href="{% url 'hostuser:dashboard' %}" class="btn btn-primary my-4">Go to Dashboard</a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </section>

</main><!-- End #main -->

{% endblock content %}

{% block javascripts %}

{% comment %} <script>

  document.getElementById("id_old_password").classList.add("form-control");
  document.getElementById("id_old_password").placeholder = "Enter Old Password";
  document.getElementById("id_new_password1").classList.add("form-control");
  document.getElementById("id_new_password1").placeholder = "Enter New Password";
  document.getElementById("id_new_password2").classList.add("form-control");
  document.getElementById("id_new_password2").placeholder = "Confirm Password";

</script> {% endcomment %}

{% endblock javascripts %}