carrental/car/urls.py
from django.urls import path
from car.views import (
                    home, 
                    listing, 
                    testimonials, 
                    about, 
                    contact, 
                    blog, 
                    singleBlog, 
                    ListingView, 
                    CarDetailView, 
                    order, 
                    RentFormView, 
                    IndexView, 
                    BookingListView, 
                    BookingDetailView, 
                    BookingCancelView,
                    SearchViewAjax, 
                    test, 
                    send_mail_to_all, 
                    schedule_mail)
from car.utils import msgfromoutside
app_name = 'car'

urlpatterns = [
    # for index
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # for search and list operations
    path('listing/', ListingView.as_view(), name='listing'),
    path('searchview/',SearchViewAjax.as_view(),name='searchviewajax'),

    # for rent operations
    path('cardetail/<int:pk>', CarDetailView.as_view(), name='cardetail'),
    path('rent/', RentFormView.as_view(), name='rent'),

    # for bookings operations
    path('bookings/', BookingListView.as_view(), name='bookings'),
    path('bookingdetail/<int:pk>', BookingDetailView.as_view(), name='bookingdetail'),
    path('bookingcancel/<int:pk>', BookingCancelView.as_view(), name='bookingcancel'),

    # for celery learning
    path('test/', test, name='test'),
    path('sendmail/', send_mail_to_all, name='sendmail'),
    path('schedulemail/', schedule_mail, name='schedulemail'),


    # for template testing only
    path('home/', home, name='home'),
    path('alllisting/', listing, name='alllisting'),
    path('testimonials/', testimonials, name='testimonials'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('blog/', blog, name='blog'),
    path('single/', singleBlog, name='single'),


    path('msg/', msgfromoutside, name='msg')
]

carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import LoginView, LogoutView

from django.conf.urls import handler400, handler403, handler404, handler500
from base.views import handler403 as customhandler403
from base.views import handler404 as customhandler404

# JWT Auth imports
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('', include('car.urls')),
    path('hostuser/', include('hostuser.urls')),

    path('account/login/', LoginView.as_view(), name='account_login'),
    path('account/logout/', LogoutView.as_view(), name='account_logout'),
    
    # for giving login option in api page
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),

    # ===============================
    # JWT AUTHENTICATION VIEWS URLS #
    # ===============================
    path('gettoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # For generate token JWT = http POST http://127.0.0.1:8000/gettoken/ username="<username>" password="<password>"
    
    path('refreshtoken/', TokenRefreshView.as_view(), name='token_refresh'),
    # For refresh token JWT = http POST http://127.0.0.1:8000/refreshtoken/ refresh="<refresh token>"


    path('verifytoken/', TokenVerifyView.as_view(), name='token_verify'),
    # For verify token JWT = http POST http://127.0.0.1:8000/verifytoken/ token="<access token>"

    path('api/user/', include('user.api.urls')),
    path('api/car/', include('car.api.urls')),
]

handler404 = handler400 = handler500 = customhandler404            
handler403 = customhandler403


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrental/user/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from user.api.views import (UserViewSet,
                            )

router = DefaultRouter()
router.register('user', UserViewSet, basename='user')

urlpatterns = [
    path('', include(router.urls))
]

carrental/user/urls.py
from django.urls import path
from user.views import (
                        UserRegisterView, 
                        registerOptionView, 
                        RegisterOptionView,
                        LoginView, 
                        CarRegisterView,
                        UserProfileUpdateView,
                        ProfileImageUpdateView,
                        PasswordsChangeView,
                        PasswordsChangeDoneView,
                        )

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('account/login/', LoginView.as_view(), name='login'),

    # path('registeroption/', registerOptionView, name='registeroption'),
    path('registeroption/', RegisterOptionView.as_view(), name='registeroption'),
    path('carregister/', CarRegisterView.as_view(), name='carregister'),

    # update profile
    path('profile/<int:pk>', UserProfileUpdateView.as_view(), name='profile'),
    path('profileimageupdate/<int:pk>', ProfileImageUpdateView.as_view(), name='profileimageupdate'),

    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),
]

carrental/car/models.py
from django.db import models
from base.models import BaseModel
from user.models import User
from django.urls import reverse_lazy

# Create your models here.


class Car(BaseModel):
    '''Car model'''
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_owner')
    brand = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    manufacture_year = models.PositiveIntegerField()
    FUEL_TYPES = (
        ("PETROL", "Petrol"),
        ("DIESEL", "Diesel"),
        ("CNG", "CNG"),
        ("EV", "Electric"),
    )
    fuel_type = models.CharField(max_length=256, choices=FUEL_TYPES, default="PETROL")
    TRANSMISSION_TYPES = (
        ("MANUAL", "Manual"),
        ("AUTOMATIC", "Automatic"),
    )
    transmission_type = models.CharField(max_length=256, choices=TRANSMISSION_TYPES, default="MANUAL")
    CAR_TYPES = (
        ("SEDAN", "Sedan"),
        ("HATCHBACK", "Hatchback"),
        ("SUV","SUV"),
        ("COUPE", "Coupe"),
    )
    car_type = models.CharField(max_length=256, choices=CAR_TYPES, default="SEDAN")
    seats = models.PositiveIntegerField()
    registration_no = models.CharField(max_length=10, unique=True)
    km_driven = models.PositiveBigIntegerField()
    fare = models.PositiveIntegerField()
    description = models.TextField(max_length=1000)
    pickup_address = models.TextField()
    pickup_city = models.CharField(max_length=256)
    pickup_state = models.CharField(max_length=256)
    pickup_country = models.CharField(max_length=256)
    pickup_pincode = models.CharField(max_length=256)
    is_available = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    def get_detail_url(self):
        return f"/hostuser/hostcardetail/{self.pk}"
    
    def get_update_url(self):
        return f"/hostuser/carupdate/{self.pk}"
    
    def get_delete_url(self):
        return f"/hostuser/cardelete/{self.pk}"


class CarImage(BaseModel):
    '''car images model'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car_image_set') # oldname = car_name
    car_images = models.ImageField(upload_to='car_images')

    def __str__(self):
        return self.car.name
    

class CarHoldTime(BaseModel):
    '''car hold time model for hostuser'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='car_carholdtime')
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()

    # def __str__(self):
    #     return self.car.name


class Rent(BaseModel):
    '''rent model for bookings data'''
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name="car_rent") # oldname = car_name
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user') # oldname = user_name
    pickup_datetime = models.DateTimeField()
    # pickup_time = models.TimeField()
    # pickup_place = models.CharField(max_length=256)
    drop_datetime = models.DateTimeField()
    # drop_time = models.TimeField()
    total_hours = models.PositiveIntegerField(default=None)
    total_fare = models.FloatField()
    BOOKING_STATUS = (
        ("CONFIRMED", "Confirmed"),
        ("PICKEDUP", "Pickedup"),
        ("DROPPED", "Dropped"),
        ("CANCELLED", "Cancelled"),
    )
    booking_status = models.CharField(max_length=256, choices=BOOKING_STATUS, default="CONFIRMED")
    PAYMENT_STATUS = (
        ("COMPLETED", "Completed"),
        ("PENDING", "Pending"),
        ("CANCELLED", "Cancelled"),
        ("REFUNDED", "Refunded"),
    )
    payment_status = models.CharField(max_length=256, choices=PAYMENT_STATUS, default="PENDING")

    # def __str__(self):
    #     return self.car.car + " " + self.user


class NotificationGroup(BaseModel):
    '''create notification group'''
    name = models.CharField(max_length=100)

class Notification(BaseModel):
    '''save notification'''
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_rent')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_car')
    group = models.ForeignKey(NotificationGroup, on_delete=models.CASCADE)
    message = models.CharField(max_length=500)
    is_read = models.BooleanField(default=False)

carrental/user/models.py
from django.db import models
from base.models import BaseModel
from django.contrib.auth.models import AbstractUser

class User(BaseModel, AbstractUser):
    '''User model for register new user'''
    contact = models.CharField(max_length=10)
    is_hostuser = models.BooleanField(default=False)
    profile_image = models.ImageField(upload_to="images/user_images", null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

carrental/user/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.db import transaction
from user.models import User
from car.models import Car, CarImage

class UserRegisterForm(UserCreationForm):
    '''form for create a new user'''
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'contact', 'password1', 'password2', 'profile_image')

        widgets = {
            'contact': forms.TextInput(attrs={'minlength':'10',}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['profile_image'].required = False


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_hostuser = False
        user.save()
        return user
    


class CarRegisterForm(ModelForm):
    '''form for create a new car from user'''
    class Meta:
        model = Car
        fields = ('brand', 'name', 'manufacture_year', 'fuel_type', 'transmission_type', 'car_type', 'seats', 'registration_no', 'km_driven', 'fare', 'description', 'pickup_address', 'pickup_city', 'pickup_state', 'pickup_country', 'pickup_pincode', 'is_active')

        widgets = {
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }

    # @transaction.atomic
    # def save(self):
    #     car = super().save(commit=False)
    #     car.owner = self.request.user
    #     car.is_available = True
    #     car.save()
    #     return car


class CarImagesForm(ModelForm):
    '''form for create images for car'''
    class Meta:
        model = CarImage
        fields = ('car_images',)

    
class UserProfileUpdateForm(ModelForm):
    '''form for update user profile'''
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'contact', 'profile_image')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'contact': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234567890'}),
            'profile_image': forms.FileInput(attrs={'class': 'form-control', "accept": "image/*"}),
        }


class UserProfileImageUpdateForm(ModelForm):
    '''form for update user profile'''
    class Meta:
        model = User
        fields = ('profile_image',)

        widgets = {
            'profile_image': forms.FileInput(attrs={'class': 'form-control', "accept": "image/*", "required":"true"}),
        }


class PasswordChangingForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Current Password', 'type': 'password'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New Password', 'type': 'password'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password', 'type': 'password'})

carrental/user/api/views.py
from car.models import Car
from user.models import User
from user.api.serializers import UserSerializer
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly, AllowAny, IsAuthenticated
from rest_framework.renderers import JSONRenderer
from user.api.permissions import IsUser
from django.db.models import Prefetch

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated, IsUser]
    renderer_classes = [JSONRenderer]

    def get_queryset(self):
        return User.objects.filter(id=self.request.user.id)

        # only gives licence number
        # return User.objects.filter(id=self.request.user.id).prefetch_related(
        #     Prefetch(
        #         'cars', 
        #         queryset=Car.objects.filter(license__is_expire=False).only("licence__number"),
        #     )
        # )


        # gives all data without licence number
         # return User.objects.filter(id=self.request.user.id).prefetch_related(
        #     Prefetch(
        #         'cars', 
        #         queryset=Car.objects.filter(license__is_expire=False).defer("licence__number"),
        #     )
        # )

carrental/templates/user/register_option.html
{% extends "user_base.html" %}
{% load static %}   
{% load crispy_forms_tags %}

{% block title %}Register - CarRental{% endblock title %}

{% block content %}

<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row mx-0">
            <div class="col-lg-6 px-0">
                <div class="px-5 d-flex align-items-center justify-content-between" style="height: 350px;background-color:#2B2E4A;">
                    <img class="img-fluid flex-shrink-0 ml-n5 w-50 mr-4" src="{% static 'images/option_car_01.png' %}" alt="">
                    <div class="text-right">
                        <h3 class="text-uppercase text-light mb-3">Looking for a car?</h3>
                        <p class="mb-4" style="color:#8486A0;">Want to going somewhere and worried about car?Now Book Car on rent and Enjoy!!</p>
                        <a class="btn py-2 px-4 text-light" href="{% url 'car:index' %}" style="background-color:#F77D0A;">Explore Now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 px-0">
                <div class="px-5 d-flex align-items-center justify-content-between" style="height: 350px;background-color:#1C1E32;">
                    <div class="text-left">
                        <h3 class="text-uppercase text-light mb-3">Want to rent your car?</h3>
                        <p class="mb-4" style="color:#8486A0;">Join our 10T+ cars Rental Community by Rent your car with us and earn!</p>
                        <a class="btn py-2 px-4 text-light" href="{% url 'user:carregister' %}" style="background-color:#F77D0A;">Register Your Car Now</a>
                    </div>
                    <img class="img-fluid flex-shrink-0 mr-n5 w-50 ml-4" src="{% static 'images/option_car_02.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}




{% comment %} color code {% endcomment %}
{% comment %} --primary: #F77D0A;
    --text: #8486A0
    --secondary: #2B2E4A;
    --light: #F4F5F8;
    --dark: #1C1E32; {% endcomment %}

carrental/templates/user/user_login.html
{% extends "user_base.html" %}
{% load static %}   
{% load crispy_forms_tags %}

{% block title %}Register - CarRental{% endblock title %}

{% block content %}

{% comment %} 'https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp' {% endcomment %}
<section class="vh-100 bg-image"
  style="background-image: url({% static 'images/hero_1_a.jpg' %});">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Login</h2>

              <form method="POST">
                {% csrf_token %}

                {{ form|crispy }}
                
                {% comment %} <div class="form-outline mb-2">
                  {{ form.email|as_crispy_field }}
                </div>

                <div class="form-outline mb-5">
                  {{ form.password|as_crispy_field}}
                </div> {% endcomment %}

                <div class="d-flex justify-content-center">
                  <input type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body" name="login" value="Login">
                </div>

                <p class="text-center text-muted mt-5 mb-0">New User? <a href="{% url 'user:register' %}"
                    class="fw-bold text-body"><u>Register here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

carrental/templates/user/user_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}CarRental - Profile {% endblock title %}

{% block stylesheet %}
    <style>
        .hero.inner-page, .hero.inner-page > .container > .row {
        height: 10vh !important;
        min-height: 80px;
        }
        .img-account-profile {
            height: 10rem;
        }
        .rounded-circle {
            border-radius: 50% !important;
        }
        .nav-tabs-bordered .nav-link.active {
            background-color: #fff;
            color: #007bff;
            border-bottom: 2px solid #007bff;
        }
    </style>
{% endblock stylesheet %}

{% block content %}



    <div class="hero inner-page" style="background-image: url({% static 'images/hero_1_a.jpg' %});"></div>
    <hr>
    {% include "messages.html" %}
  <section class="container">
    <div class="container-xl px-4 mt-4">
        <hr class="mt-0 mb-4">
        <div class="row">
            <div class="col-xl-4">
                <!-- Profile picture card-->
                <div class="card mb-4 mb-xl-0">
                    <div class="card-header text-center">Profile Picture</div>
                    <div class="card-body text-center">
                        <!-- Profile picture image-->
                        {% if user.profile_image %}
                            <img src="{{ user.profile_image.url }}" alt="Profile" class="img-account-profile rounded-circle mb-2">
                        {% else %}
                            <img src="{% static 'images/profile_image.webp' %}" alt="Profile" class="img-account-profile rounded-circle mb-2">
                        {% endif %}
                        <!-- Profile picture help block-->
                        <div class="font-italic text-muted mt-2 mb-4">
                            <h5>{{ user.first_name }} {{ user.last_name }}</h5>
                            <h6>{{ user.email }}</h6>
                        </div>
                        <!-- Profile picture upload button-->
                        <button type="button" class="btn btn-sm btn-primary mt-2" data-toggle="modal" data-target="#profileImageUpdateModal">
                            Change Photo
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-xl-8">
                <!-- Bordered Tabs -->
                <ul class="nav nav-tabs nav-tabs-bordered">

                    <li class="nav-item mr-1">
                    <button class="nav-link active" data-toggle="tab" data-target="#profile-overview">Overview</button>
                    </li>
    
                    <li class="nav-item mr-1">
                    <button class="nav-link" data-toggle="tab" data-target="#profile-edit">Edit Profile</button>
                    </li>
    
                    <li class="nav-item mr-1">
                    <button class="nav-link" data-toggle="tab" id="changePasswordTab" data-target="#profile-change-password">Change Password</button>
                    </li>
    
                </ul>
                
                <div class="tab-content pt-2">
                    <div class="tab-pane fade show active profile-overview card p-3" id="profile-overview">
                        <h5 class="ml-2 mt-3 card-title text-primary">Profile Details</h5>
                        <hr class="bg-dark">
                        <div class="row">
                        <div class="ml-2 col-lg-3 col-md-4 label">Username:</div>
                        <div class="mr-2 col-lg-8 col-md-7">{{ user.username }}</div>
                        </div>

                        <div class="row">
                        <div class="ml-2 col-lg-3 col-md-4 label">Full Name:</div>
                        <div class="mr-2 col-lg-8 col-md-8">{{ user.first_name }} {{ user.last_name }}</div>
                        </div>

                        <div class="row">
                        <div class="ml-2 col-lg-3 col-md-4 label">Phone:</div>
                        <div class="mr-2 col-lg-8 col-md-8">{{ user.contact }}</div>
                        </div>

                        <div class="row">
                        <div class="ml-2 col-lg-3 col-md-4 label">Email:</div>
                        <div class="mr-2 col-lg-8 col-md-8">{{ user.email }}</div>
                        </div>
                    </div>

                    <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                        <!-- Profile Edit Form -->
                        <form method="POST" id="profileUpdateForm">
                          {% csrf_token %}
                          {% comment %} <div class="row mb-3">
                            <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                            <div class="col-md-8 col-lg-9">
                              <img src="assets/img/profile-img.jpg" alt="Profile">
                              <div class="pt-2">
                                <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                                <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                              </div>
                            </div>
                          </div> {% endcomment %}
        
                          <div class="row mb-3">
                            <label for="username" class="col-md-4 col-lg-3 col-form-label">Username</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="username" type="text" class="form-control" id="username" value="{{ user.username }}" disabled>
                              <p class="text-danger">* You can not change your username</p>
                            </div>
                          </div>
        
                          <div class="row mb-3">
                            <label for="id_first_name" class="col-md-4 col-lg-3 col-form-label">First Name</label>
                            <div class="col-md-8 col-lg-9">
                              {{ form.first_name }}
                            </div>
                          </div>
        
                          <div class="row mb-3">
                            <label for="id_last_name" class="col-md-4 col-lg-3 col-form-label">Last Name</label>
                            <div class="col-md-8 col-lg-9">
                              {{ form.last_name }}
                            </div>
                          </div>
        
                          <div class="row mb-3">
                            <label for="id_contact" class="col-md-4 col-lg-3 col-form-label">Phone</label>
                            <div class="col-md-8 col-lg-9">
                              {{ form.contact }}
                            </div>
                          </div>
        
                          <div class="row mb-3">
                            <label for="email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="email" type="email" class="form-control" id="email" value="{{ user.email }}" disabled>
                              <p class="text-danger">* You can not change your email</p>
                            </div>
                          </div>
                        
        
                          <div class="text-center">
                            <button type="submit" form="profileUpdateForm" class="btn btn-primary">Save Changes</button>
                          </div>
                        </form><!-- End Profile Edit Form -->
        
                    </div>

                    <div class="tab-pane fade pt-3 profile-change-password" id="profile-change-password">
                      
                      <!-- Change Password Form -->
                      <form action="{% url 'user:password_change' %}" method="POST" id="passwordChangeForm">
                        {% csrf_token %} 
                        
                        
                        <div class="row mb-3">
                          <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                          <div class="col-md-8 col-lg-9">
                            {{ passform.old_password }}
                            {% comment %} <input name="password" type="password" class="form-control" id="currentPassword"> {% endcomment %}
                          </div>
                        </div>
                        <span class="text-danger">{{ passform.old_password.errors }}</span>
                  
                        <div class="row mb-3">
                          <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                          <div class="col-md-8 col-lg-9">
                            {{ passform.new_password1 }}
                            {% comment %} <input name="newpassword" type="password" class="form-control" id="newPassword"> {% endcomment %}
                          </div>
                        </div>
                        <span class="text-danger">{{ passform.new_password1.errors }}</span>
                  
                        <div class="row mb-3">
                          <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                          <div class="col-md-8 col-lg-9">
                            {{ passform.new_password2 }}
                            {% comment %} <input name="renewpassword" type="password" class="form-control" id="renewPassword"> {% endcomment %}
                          </div>
                        </div>
                        <span class="text-danger">{{ passform.new_password2.errors }}</span>
                        
                        <div class="text-center">
                          <button type="submit" form="passwordChangeForm" class="btn btn-primary change-password-btn">Change Password</button>
                        </div>
                        
                      </form><!-- End Change Password Form -->
                  
                    </div>

                </div>
              
              
            </div>
        </div>
    </div>

  </section>

  <!-- Profile Image Update Modal Start -->
  <div class="modal fade" id="profileImageUpdateModal" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Change Profile Image</h5>
          <button type="button" class="btn" data-dismiss="modal" aria-label="Close">&times;</button>
        </div>
        <div class="modal-body">
          {% comment %}  action={% url 'user:profileimageupdate' pk=request.user.id %} {% endcomment %}
          <form method="POST" action={% url 'user:profileimageupdate' pk=request.user.id %} enctype="multipart/form-data" id="imageupdateform">
            {% csrf_token %}
            <div class="col-md-12">
              {{imageform.profile_image}}
              {% comment %} <input type="file" class="form-control" name="profile_image" id="profile_image" accept="image/*"> {% endcomment %}
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" form="imageupdateform" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Profile Image Update Modal End -->


{% endblock content %}

{% block javascripts %}

{% comment %} <script>


  $(".change-password-btn").on('click', function(event){
    console.log(":::::::;;;;");
    event.preventDefault();
    $.ajax({
      //url: "{% url 'user:password_change' %}",
      type: 'POST',
      data: {
        "csrfmiddlewaretoken": '{{ csrf_token }}'
      },
      success: function(res) {
        console.log(res);
        
      },
      error: function(error) {
        console.log('error', error);
      }
    });
  });

</script> {% endcomment %}

{% endblock javascripts %}