carrental/car/urls.py
from django.urls import path
from car.views import (
                    home, 
                    listing, 
                    testimonials, 
                    about, 
                    contact, 
                    blog, 
                    singleBlog, 
                    ListingView, 
                    CarDetailView, 
                    order, 
                    RentFormView, 
                    IndexView, 
                    BookingListView, 
                    BookingDetailView, 
                    BookingCancelView,
                    SearchViewAjax, 
                    test, 
                    send_mail_to_all, 
                    schedule_mail)
from car.utils import msgfromoutside
app_name = 'car'

urlpatterns = [
    # for index
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # for search and list operations
    path('listing/', ListingView.as_view(), name='listing'),
    path('searchview/',SearchViewAjax.as_view(),name='searchviewajax'),

    # for rent operations
    path('cardetail/<int:pk>', CarDetailView.as_view(), name='cardetail'),
    path('rent/', RentFormView.as_view(), name='rent'),

    # for bookings operations
    path('bookings/', BookingListView.as_view(), name='bookings'),
    path('bookingdetail/<int:pk>', BookingDetailView.as_view(), name='bookingdetail'),
    path('bookingcancel/<int:pk>', BookingCancelView.as_view(), name='bookingcancel'),

    # for celery learning
    path('test/', test, name='test'),
    path('sendmail/', send_mail_to_all, name='sendmail'),
    path('schedulemail/', schedule_mail, name='schedulemail'),


    # for template testing only
    path('home/', home, name='home'),
    path('alllisting/', listing, name='alllisting'),
    path('testimonials/', testimonials, name='testimonials'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('blog/', blog, name='blog'),
    path('single/', singleBlog, name='single'),


    path('msg/', msgfromoutside, name='msg')
]

carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import LoginView, LogoutView

from django.conf.urls import handler400, handler403, handler404, handler500
from base.views import handler403 as customhandler403
from base.views import handler404 as customhandler404

# JWT Auth imports
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('', include('car.urls')),
    path('hostuser/', include('hostuser.urls')),

    path('account/login/', LoginView.as_view(), name='account_login'),
    path('account/logout/', LogoutView.as_view(), name='account_logout'),
    
    # for giving login option in api page
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),

    # ===============================
    # JWT AUTHENTICATION VIEWS URLS #
    # ===============================
    path('gettoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # For generate token JWT = http POST http://127.0.0.1:8000/gettoken/ username="<username>" password="<password>"
    
    path('refreshtoken/', TokenRefreshView.as_view(), name='token_refresh'),
    # For refresh token JWT = http POST http://127.0.0.1:8000/refreshtoken/ refresh="<refresh token>"


    path('verifytoken/', TokenVerifyView.as_view(), name='token_verify'),
    # For verify token JWT = http POST http://127.0.0.1:8000/verifytoken/ token="<access token>"

    path('api/user/', include('user.api.urls')),
    path('api/car/', include('car.api.urls')),
]

handler404 = handler400 = handler500 = customhandler404            
handler403 = customhandler403


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrental/hostuser/urls.py
from django.urls import path
from hostuser.views import (
                            DashboardView, 
                            AjaxRevenueChartDataView,
                            HostCarDetailView, 
                            HostUserProfileUpdateView,
                            HostProfileImageUpdateView, 
                            CarListView, 
                            CarListDataTablesAjaxPagination,
                            CarUpdateView, 
                            CarDeleteView, 
                            HostBookingListView, 
                            HostBookingListDataTablesAjaxPagination,
                            HostBookingDetailView, 
                            HostBookingUpdateView, 
                            CarHoldTimeCreateView, 
                            HoldCarListView, 
                            HoldCarListDataTablesAjaxPagination,
                            CarHoldTimeUpdateView, 
                            CarHoldTimeDeleteView,
                            AjaxCarAvailabilityCheckView,
                            CustomersListView,
                            CustomersListDataTablesAjaxPagination,
                            SingleCarImageDeleteView,
                            RevenueCompareView,
                            RevenueCompareAjax,
                            PasswordsChangeView,
                            PasswordsChangeDoneView,
                            NotificationReadAjaxView,
                        )
# from car.views import HostCarDeleteView

app_name = 'hostuser'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('revenue-chart-ajax/', AjaxRevenueChartDataView.as_view(), name='revenue-chart-ajax'),

    # car CRUD (Car create view is inside user app)
    path('carlist/', CarListView.as_view(), name='carlist'),
    path('car-list-ajax/',CarListDataTablesAjaxPagination.as_view(), name='car-list-ajax'),
    path('carupdate/<int:pk>', CarUpdateView.as_view(), name='carupdate'),
    path('hostcardetail/<int:pk>', HostCarDetailView.as_view(), name='hostcardetail'),
    path('cardelete/<int:pk>', CarDeleteView.as_view(), name='cardelete'),
    path('singlecarimagedelete/<int:pk>', SingleCarImageDeleteView.as_view(), name='singlecarimagedelete'),

    # update profile
    path('hostprofile/<int:pk>', HostUserProfileUpdateView.as_view(), name='hostprofile'),
    path('hostprofileimageupdate/<int:pk>', HostProfileImageUpdateView.as_view(), name='hostprofileimageupdate'),

    # booking CRUD
    path('hostbookinglist/', HostBookingListView.as_view(), name='hostbookinglist'),
    path('booking-list-ajax/',HostBookingListDataTablesAjaxPagination.as_view(), name='booking-list-ajax'),
    path('hostbookingdetail/<int:pk>', HostBookingDetailView.as_view(), name='hostbookingdetail'),
    path('hostbookingupdate/<int:pk>', HostBookingUpdateView.as_view(), name='hostbookingupdate'),

    # car hold CRUD
    path('carhold/', CarHoldTimeCreateView.as_view(), name='carhold'),
    path('holdcarlist/', HoldCarListView.as_view(), name='holdcarlist'),
    path('hold-car-list-ajax/',HoldCarListDataTablesAjaxPagination.as_view(), name='hold-car-list-ajax'),
    path('carholdupdate/<int:pk>', CarHoldTimeUpdateView.as_view(), name='carholdupdate'),
    path('carholddelete/<int:pk>', CarHoldTimeDeleteView.as_view(), name='carholddelete'),

    # check car availability using ajax
    path("ajax-car-availability/", AjaxCarAvailabilityCheckView.as_view(),  name="ajax_car_availability_check"),

    # customers list
    path('customerslist/', CustomersListView.as_view(), name='customerslist'),
    path('customers-list-ajax/',CustomersListDataTablesAjaxPagination.as_view(), name='customers-list-ajax'),

    # revenue compare
    path('revenue-compare/', RevenueCompareView.as_view(), name="revenue-compare"),
    path('revenue-compare-ajax/', RevenueCompareAjax.as_view(), name="revenue-compare-ajax"),


    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),

    # notification
    path('notification_read_status/', NotificationReadAjaxView.as_view(), name='notification_read_status'),
]

carrental/user/urls.py
from django.urls import path
from user.views import (
                        UserRegisterView, 
                        registerOptionView, 
                        RegisterOptionView,
                        LoginView, 
                        CarRegisterView,
                        UserProfileUpdateView,
                        ProfileImageUpdateView,
                        PasswordsChangeView,
                        PasswordsChangeDoneView,
                        )

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('account/login/', LoginView.as_view(), name='login'),

    # path('registeroption/', registerOptionView, name='registeroption'),
    path('registeroption/', RegisterOptionView.as_view(), name='registeroption'),
    path('carregister/', CarRegisterView.as_view(), name='carregister'),

    # update profile
    path('profile/<int:pk>', UserProfileUpdateView.as_view(), name='profile'),
    path('profileimageupdate/<int:pk>', ProfileImageUpdateView.as_view(), name='profileimageupdate'),

    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),
]

carrental/templates/hostuser_base/hostuser_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    {% block stylesheet %}{% endblock stylesheet %}
    
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <!-- ======= Header ======= -->
    {% include "hostuser_base/hostuser_navbar.html" %}
    <!-- End Header -->

    <!-- ======= Sidebar ======= -->
    {% include "hostuser_base/hostuser_sidebar.html" %}
    <!-- End Sidebar -->

    <!-- ======= content ======= -->


    {% block content %}
    

    {% endblock content %}
    <!-- End content -->

    <!-- ======= Footer ======= -->
    {% comment %} {% include "hostuser_base/hostuser_footer.html" %} {% endcomment %}
    <!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    
    
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    
    <!-- Jquery Cdn -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Sweet Alert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!-- Js for Notification Websocket connection -->
    <script>
        const notificationSocket = new WebSocket(
          'ws://'
          + window.location.host
          + '/ws/notification/'
        );
      
        notificationSocket.onmessage = function(e) {
          const data = JSON.parse(e.data);
          console.log(data.message);
          //document.querySelector("#note").innerHTML += (data.message + '\n');
          $("#noti-div").load(" #noti-div > *");
        }
      
        notificationSocket.onclose = function(e) {
          console.error("Notification Socket closed unexpectedly");
        }
      
    </script>

    <!-- Js for Change notification is_read status -->
    <script>
  
        function notificationRead(id){

            message_id = id;
            console.log("message id :", message_id);

            $.ajax({
            url: "{% url 'hostuser:notification_read_status' %}",
            type: 'GET',
            data : {
                "message_id": message_id,
            },
            success: function(res) {
                $("#noti-div").load(" #noti-div > *");
            }
            });
        
        }

    </script>
    
    <!-- Specific JS goes HERE --> 
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

carrental/templates/hostuser_base/hostuser_cardetail_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock stylesheet %}
</head>
<body>
    <!-- ======= Header ======= -->
    {% include "hostuser_base/hostuser_navbar.html" %}
    <!-- End Header -->

    <!-- ======= Sidebar ======= -->
    {% comment %} {% include "hostuser_base/hostuser_sidebar.html" %} {% endcomment %}
    <!-- End Sidebar -->

    <!-- ======= content ======= -->
    {% block content %}{% endblock content %}
    <!-- End content -->

    <!-- ======= Footer ======= -->
    {% comment %} {% include "hostuser_base/hostuser_footer.html" %} {% endcomment %}
    <!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Specific JS goes HERE --> 
    {% block javascripts %}{% endblock javascripts %}


    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

carrental/templates/hostuser_base/hostuser_footer.html
{% load static %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

carrental/templates/hostuser_base/hostuser_navbar.html
{% load static %}

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'hostuser:dashboard' %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">CarRental</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    {% comment %} <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar --> {% endcomment %}

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown" id="noti-div">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">{{ notifications_count }}</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have {{ notifications_count }} new notifications
              {% comment %} <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a> {% endcomment %}
            </li>
            <li id="add_notification">
              <hr class="dropdown-divider">
            </li>
            {% for notification in notifications %}
              <li class="notification-item">
                <i class="bi bi-check-circle text-success"></i>
                <div>
                  <h4>New Booking</h4>
                  <p id="noti_message">{{ notification.message }}</p>
                  {% comment %} <p>2 hrs. ago</p> {% endcomment %}
                </div>
                <button type="button" data-id="{{notification.id}}" class="btn btn-sm" id="is_read_{{notification.id}}" onclick="notificationRead({{notification.id}})"><i class="fa fa-close"></i></button>
              </li>
              
              <li>
                <hr class="dropdown-divider">
              </li>
            {% endfor %}


            {% comment %} <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li> {% endcomment %}

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item" style="margin-right:20px;">

          <a class="btn btn-primary" href="{% url 'user:carregister' %}">
            <i class="bi bi-plus mr-1"></i>Add Car
          </a><!-- End Add Car Button -->

        </li>
        <li class="nav-item mt-3" style="margin-right:20px;">

          <div class="form-floating mb-3">
            <select class="form-select" id="floatingSelect" onchange="location = this.value";>
              <option value="{% url 'hostuser:dashboard' %}" selected="">Admin</option>
              <option value="{% url 'car:index' %}">User</option>
            </select>
            <label for="floatingSelect">View As</label>
          </div>

        </li><!-- End User Type Select -->
        <!-- End Notification Nav -->
        
        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" alt="Profile" class="rounded-circle">
            {% else %}
            <img src="{% static 'images/profile_image.webp' %}" alt="Profile" class="rounded-circle">
            {% endif %}
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ request.user }}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'hostuser:hostprofile' pk=request.user.id %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'account_logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Logout</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

carrental/templates/hostuser_base/hostuser_sidebar.html
{% load static %}

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link {% if 'dashboard' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link {% if 'carlist' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:carlist' %}">
          <i class="ri-car-line"></i>
          <span>Car List</span>
        </a>
      </li><!-- End Car List Nav -->

      <li class="nav-item">
        <a class="nav-link {% if 'hostbookinglist' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:hostbookinglist' %}">
          <i class="ri-file-list-3-line"></i>
          <span>Booking List</span>
        </a>
      </li><!-- End Car List Nav -->

      <li class="nav-item">
        <a class="nav-link {% if 'holdcarlist' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:holdcarlist' %}">
          <i class="fa fa-circle-stop"></i>
          <span>Hold Car List</span>
        </a>
      </li><!-- End Hold Car List Nav -->

      <li class="nav-item">
        <a class="nav-link {% if 'customerslist' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:customerslist' %}">
          <i class="fa fa-users"></i>
          <span>Customers List</span>
        </a>
      </li><!-- End Customers List Nav -->

      <li class="nav-item">
        <a class="nav-link {% if 'revenue-compare' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:revenue-compare' %}">
          <i class="fas fa-dollar-sign"></i>
          <span>Revenue Compare</span>
        </a>
      </li><!-- End Revenue Compare Nav -->
      

      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link {% if 'hostprofile' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'hostuser:hostprofile' pk=request.user.id %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'account_logout' %}">
          <i class="bi bi-box-arrow-in-right"></i>
          <span>Logout</span>
        </a>
      </li><!-- End Login Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->