carrental/car/urls.py
from django.urls import path
from car.views import (
                    home, 
                    listing, 
                    testimonials, 
                    about, 
                    contact, 
                    blog, 
                    singleBlog, 
                    ListingView, 
                    CarDetailView, 
                    order, 
                    RentFormView, 
                    IndexView, 
                    BookingListView, 
                    BookingDetailView, 
                    BookingCancelView,
                    SearchViewAjax, 
                    test, 
                    send_mail_to_all, 
                    schedule_mail)
from car.utils import msgfromoutside
app_name = 'car'

urlpatterns = [
    # for index
    path('', IndexView.as_view(), name='index'),
    path('index/', IndexView.as_view(), name='index'),

    # for search and list operations
    path('listing/', ListingView.as_view(), name='listing'),
    path('searchview/',SearchViewAjax.as_view(),name='searchviewajax'),

    # for rent operations
    path('cardetail/<int:pk>', CarDetailView.as_view(), name='cardetail'),
    path('rent/', RentFormView.as_view(), name='rent'),

    # for bookings operations
    path('bookings/', BookingListView.as_view(), name='bookings'),
    path('bookingdetail/<int:pk>', BookingDetailView.as_view(), name='bookingdetail'),
    path('bookingcancel/<int:pk>', BookingCancelView.as_view(), name='bookingcancel'),

    # for celery learning
    path('test/', test, name='test'),
    path('sendmail/', send_mail_to_all, name='sendmail'),
    path('schedulemail/', schedule_mail, name='schedulemail'),


    # for template testing only
    path('home/', home, name='home'),
    path('alllisting/', listing, name='alllisting'),
    path('testimonials/', testimonials, name='testimonials'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('blog/', blog, name='blog'),
    path('single/', singleBlog, name='single'),


    path('msg/', msgfromoutside, name='msg')
]

carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import LoginView, LogoutView

from django.conf.urls import handler400, handler403, handler404, handler500
from base.views import handler403 as customhandler403
from base.views import handler404 as customhandler404

# JWT Auth imports
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('', include('car.urls')),
    path('hostuser/', include('hostuser.urls')),

    path('account/login/', LoginView.as_view(), name='account_login'),
    path('account/logout/', LogoutView.as_view(), name='account_logout'),
    
    # for giving login option in api page
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),

    # ===============================
    # JWT AUTHENTICATION VIEWS URLS #
    # ===============================
    path('gettoken/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # For generate token JWT = http POST http://127.0.0.1:8000/gettoken/ username="<username>" password="<password>"
    
    path('refreshtoken/', TokenRefreshView.as_view(), name='token_refresh'),
    # For refresh token JWT = http POST http://127.0.0.1:8000/refreshtoken/ refresh="<refresh token>"


    path('verifytoken/', TokenVerifyView.as_view(), name='token_verify'),
    # For verify token JWT = http POST http://127.0.0.1:8000/verifytoken/ token="<access token>"

    path('api/user/', include('user.api.urls')),
    path('api/car/', include('car.api.urls')),
]

handler404 = handler400 = handler500 = customhandler404            
handler403 = customhandler403


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrental/hostuser/urls.py
from django.urls import path
from hostuser.views import (
                            DashboardView, 
                            AjaxRevenueChartDataView,
                            HostCarDetailView, 
                            HostUserProfileUpdateView,
                            HostProfileImageUpdateView, 
                            CarListView, 
                            CarListDataTablesAjaxPagination,
                            CarUpdateView, 
                            CarDeleteView, 
                            HostBookingListView, 
                            HostBookingListDataTablesAjaxPagination,
                            HostBookingDetailView, 
                            HostBookingUpdateView, 
                            CarHoldTimeCreateView, 
                            HoldCarListView, 
                            HoldCarListDataTablesAjaxPagination,
                            CarHoldTimeUpdateView, 
                            CarHoldTimeDeleteView,
                            AjaxCarAvailabilityCheckView,
                            CustomersListView,
                            CustomersListDataTablesAjaxPagination,
                            SingleCarImageDeleteView,
                            RevenueCompareView,
                            RevenueCompareAjax,
                            PasswordsChangeView,
                            PasswordsChangeDoneView,
                            NotificationReadAjaxView,
                        )
# from car.views import HostCarDeleteView

app_name = 'hostuser'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('revenue-chart-ajax/', AjaxRevenueChartDataView.as_view(), name='revenue-chart-ajax'),

    # car CRUD (Car create view is inside user app)
    path('carlist/', CarListView.as_view(), name='carlist'),
    path('car-list-ajax/',CarListDataTablesAjaxPagination.as_view(), name='car-list-ajax'),
    path('carupdate/<int:pk>', CarUpdateView.as_view(), name='carupdate'),
    path('hostcardetail/<int:pk>', HostCarDetailView.as_view(), name='hostcardetail'),
    path('cardelete/<int:pk>', CarDeleteView.as_view(), name='cardelete'),
    path('singlecarimagedelete/<int:pk>', SingleCarImageDeleteView.as_view(), name='singlecarimagedelete'),

    # update profile
    path('hostprofile/<int:pk>', HostUserProfileUpdateView.as_view(), name='hostprofile'),
    path('hostprofileimageupdate/<int:pk>', HostProfileImageUpdateView.as_view(), name='hostprofileimageupdate'),

    # booking CRUD
    path('hostbookinglist/', HostBookingListView.as_view(), name='hostbookinglist'),
    path('booking-list-ajax/',HostBookingListDataTablesAjaxPagination.as_view(), name='booking-list-ajax'),
    path('hostbookingdetail/<int:pk>', HostBookingDetailView.as_view(), name='hostbookingdetail'),
    path('hostbookingupdate/<int:pk>', HostBookingUpdateView.as_view(), name='hostbookingupdate'),

    # car hold CRUD
    path('carhold/', CarHoldTimeCreateView.as_view(), name='carhold'),
    path('holdcarlist/', HoldCarListView.as_view(), name='holdcarlist'),
    path('hold-car-list-ajax/',HoldCarListDataTablesAjaxPagination.as_view(), name='hold-car-list-ajax'),
    path('carholdupdate/<int:pk>', CarHoldTimeUpdateView.as_view(), name='carholdupdate'),
    path('carholddelete/<int:pk>', CarHoldTimeDeleteView.as_view(), name='carholddelete'),

    # check car availability using ajax
    path("ajax-car-availability/", AjaxCarAvailabilityCheckView.as_view(),  name="ajax_car_availability_check"),

    # customers list
    path('customerslist/', CustomersListView.as_view(), name='customerslist'),
    path('customers-list-ajax/',CustomersListDataTablesAjaxPagination.as_view(), name='customers-list-ajax'),

    # revenue compare
    path('revenue-compare/', RevenueCompareView.as_view(), name="revenue-compare"),
    path('revenue-compare-ajax/', RevenueCompareAjax.as_view(), name="revenue-compare-ajax"),


    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),

    # notification
    path('notification_read_status/', NotificationReadAjaxView.as_view(), name='notification_read_status'),
]

carrental/user/urls.py
from django.urls import path
from user.views import (
                        UserRegisterView, 
                        registerOptionView, 
                        RegisterOptionView,
                        LoginView, 
                        CarRegisterView,
                        UserProfileUpdateView,
                        ProfileImageUpdateView,
                        PasswordsChangeView,
                        PasswordsChangeDoneView,
                        )

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('account/login/', LoginView.as_view(), name='login'),

    # path('registeroption/', registerOptionView, name='registeroption'),
    path('registeroption/', RegisterOptionView.as_view(), name='registeroption'),
    path('carregister/', CarRegisterView.as_view(), name='carregister'),

    # update profile
    path('profile/<int:pk>', UserProfileUpdateView.as_view(), name='profile'),
    path('profileimageupdate/<int:pk>', ProfileImageUpdateView.as_view(), name='profileimageupdate'),

    # password change
    path('password_change/', PasswordsChangeView.as_view(), name='password_change'),
    path('password_success/', PasswordsChangeDoneView.as_view(), name='password_success'),
]

carrental/base/models.py
from django.db import models

# Create your models here.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

carrental/base/views.py
from django.shortcuts import render

# Create your views here.

def handler404(request, *args, **kwargs):
    return render(request, '404.html', status=404)

def handler403(request, *args, **kwargs):
    return render(request, '403.html', status=403)

carrental/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static '/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static '/css/aos.css' %}">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    {% block stylesheet %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="site-wrap" id="home-section">

        <!-- Navbar -->
        {% include "navbar.html" %}

        
        {% block content %}{% endblock content %}

        <!-- Footer -->
        {% block footer %}{% endblock footer %}

    </div>

    
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '/js/jquery.sticky.js' %}"></script>
    <script src="{% static '/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static '/js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static '/js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static '/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static '/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static '/js/aos.js' %}"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <!-- Slick Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <!-- Font Awesome Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js" integrity="sha512-uKQ39gEGiyUJl4AI6L+ekBdGKpGw4xJ55+xyJG7YFlJokPNYegn9KwQ3P8A7aFQAUtUsAQHep+d/lrGqrbPIDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Sweet Alert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="{% static '/js/main.js' %}"></script>

    <!-- Specific JS goes HERE --> 
    {% block javascripts %}{% endblock javascripts %}
    
</body>
</html>

carrental/templates/footer.html
<div class="site-section bg-primary py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7 mb-4 mb-md-0">
          <h2 class="mb-0 text-white">What are you waiting for?</h2>
          <p class="mb-0 opa-7">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
        </div>
        <div class="col-lg-5 text-md-right">
          <a href="#" class="btn btn-primary btn-white">Rent a car now</a>
        </div>
      </div>
    </div>
  </div>

    
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="footer-heading mb-4">About Us</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            <ul class="list-unstyled social">
              <li><a href="#"><span class="icon-facebook"></span></a></li>
              <li><a href="#"><span class="icon-instagram"></span></a></li>
              <li><a href="#"><span class="icon-twitter"></span></a></li>
              <li><a href="#"><span class="icon-linkedin"></span></a></li>
            </ul>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Resources</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Support</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Company</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made by Bhavin Shiyaniya
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

carrental/templates/messages.html
{% if messages %}
{% for message in messages %}
  <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

carrental/templates/navbar.html
    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>



    <header class="site-navbar site-navbar-target" role="banner">

      <div class="container">
        <div class="row align-items-center position-relative">

          <div class="col-3">
            <div class="site-logo">
              <a href="{% url 'car:index' %}"><strong>CarRental</strong></a>
            </div>
          </div>

          <div class="col-9  text-right">
            
            <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

            <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
              <ul class="site-menu main-menu js-clone-nav ml-auto ">
                <li class="active"><a href="{% url 'car:index' %}" class="nav-link">Home</a></li>

                
                <li><a href="{% url 'car:listing' %}" class="nav-link">Listing</a></li>
                {% comment %} <li><a href="{% url 'testimonials' %}" class="nav-link">Testimonials</a></li> {% endcomment %}
                {% comment %} <li><a href="{% url 'blog' %}" class="nav-link">Blog</a></li> {% endcomment %}
                {% comment %} <li><a href="{% url 'about' %}" class="nav-link">About</a></li> {% endcomment %}
                {% comment %} <li><a href="{% url 'contact' %}" class="nav-link">Contact</a></li> {% endcomment %}
                
                {% if user.is_authenticated %}
                {% if request.user.is_hostuser == True %}
                <li class="nav-item dropdown ms-auto">
                  <a href="#" class="nav-link dropdown-toggle text-primary" data-toggle="dropdown">View as :  User</a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <a href="{% url 'hostuser:dashboard' %}" class="dropdown-item">Admin</a>
                    <a href="{% url 'car:index' %}" class="dropdown-item text-primary">User</a>
                  </div>
                </li>
                {% else %}
                <li><a href="{% url 'user:carregister' %}" class="nav-link">Register Car</a></li>
                {% endif %}

               

                <li class="nav-item dropdown ms-auto">
                  <a href="#" class="nav-link dropdown-toggle text-danger" data-toggle="dropdown">{{ request.user.first_name }}</a>
                  <div class="dropdown-menu dropdown-menu-end">
                    {% comment %} <a href="#" class="dropdown-item">Reports</a> {% endcomment %}
                    <a href="{% url 'car:bookings' %}" class="dropdown-item">My Bookings</a>
                    <a href="{% url 'user:profile' pk=request.user.id %}" class="dropdown-item">Profile</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
                  </div>
                </li>
                {% else %}
                <li><a href="{% url 'user:register' %}" class="nav-link">Register</a></li>
                <li><a href="{% url 'account_login' %}" class="nav-link">Login</a></li>
                {% endif %}

              </ul>
            </nav>
          </div>

          
        </div>
      </div>

    </header>

carrental/templates/user_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static '/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static '/css/aos.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    {% block customcss %}
    <style>
        
        /* css for user register form */

        .gradient-custom-3 {
        /* fallback for old browsers */
        background: #84fab0;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(132, 250, 176, 0.5), rgba(143, 211, 244, 0.5));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(132, 250, 176, 0.5), rgba(143, 211, 244, 0.5))
        }
        .gradient-custom-4 {
        /* fallback for old browsers */
        background: #84fab0;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(132, 250, 176, 1), rgba(143, 211, 244, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(132, 250, 176, 1), rgba(143, 211, 244, 1))
        }
    
    </style>
    {% endblock customcss%}


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="site-wrap" id="home-section">
        {% include "navbar.html" %}
        
        {% block content %}{% endblock content %}


    </div>

    <!-- Specific JS goes HERE --> 
    {% block javascripts %}{% endblock javascripts %}

    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '/js/jquery.sticky.js' %}"></script>
    <script src="{% static '/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static '/js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static '/js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static '/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static '/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static '/js/aos.js' %}"></script>

    <script src="{% static '/js/main.js' %}"></script>
</body>
</html>